const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const context = vm.createContext({crypto:require('node:crypto').webcrypto,Date,Math});
vm.runInContext(fs.readFileSync(path.join(__dirname,'core.js'),'utf8')+'\nglobalThis.core = StoryCore;',context);
const core = context.core;
const image = 'data:image/png;base64,aW1hZ2U=';
const firstAudio = {data:'data:audio/webm;codecs=opus;base64,YXVkaW8=',duration:3.25};
const previousAudio = {data:'data:audio/mp4;base64,b2xk',duration:2.25};
const book = {title:'우리 동화',author:'딸',pages:[{...core.page('art:rabbit','안녕, 토끼야!'),audio:firstAudio,previousAudio},core.page(image,'다음 장') ]};
const packed = core.pack(book,{rabbit:image});
const imported = core.validate(JSON.parse(JSON.stringify(packed)));
assert.equal(imported.title,book.title);
assert.equal(imported.author,book.author);
assert.equal(imported.pages[0].image,image);
assert.equal(imported.pages[0].decorated,true);
assert.equal(imported.pages[1].decorated,false);
assert.equal(imported.pages[0].audio.data,firstAudio.data);
assert.equal(imported.pages[0].audio.duration,3.25);
assert.equal(imported.pages[0].previousAudio.data,previousAudio.data);
assert.equal(imported.pages[1].text,'다음 장');
assert.equal(imported.pages[1].audio,null);
assert.notEqual(imported.pages[0].id,imported.pages[1].id);
assert.deepEqual(Array.from(core.missing(imported)),[1]);
assert.deepEqual(Array.from(core.missing(imported,1)),[1]);
assert.equal(core.validate(core.pack(book,{rabbit:image},false),{rabbit:image}).pages[0].image,'art:rabbit');
function reject(change) { const value = JSON.parse(JSON.stringify(packed)); change(value); assert.throws(() => core.validate(value)); }
reject(v => v.format='foreign');
reject(v => v.version=9);
reject(v => v.pages=[]);
reject(v => v.pages=Array(101).fill(v.pages[0]));
reject(v => v.pages[0].text='x'.repeat(5001));
reject(v => v.pages[0].image='https://untrusted.example/image.png');
reject(v => v.pages[0].image='data:image/svg+xml;base64,PHN2Zz4=');
reject(v => v.pages[0].image='data:image/png;base64,***=');
reject(v => v.pages[0].image='art:missing');
reject(v => v.pages[0].audio.duration=-1);
reject(v => v.pages[0].audio.data='data:text/html;base64,YXVkaW8=');
const longText = '별이 반짝였어요.\n'+'🦄'.repeat(300)+' '+ '아름다운 이야기 '.repeat(50);
const chunks = Array.from(core.splitText(longText));
assert(chunks.every(s => Array.from(s).length<=140));
assert.equal(chunks.join('').replace(/\s/g,''),longText.replace(/\s/g,''));
assert.equal(core.splitText(' \n ').length,0);
assert.equal(core.filename('꿈/나라:이야기?'),'꿈_나라_이야기_.story.json');
assert.equal(core.filename('... '),'나의 동화책.story.json');
const html = fs.readFileSync(path.join(__dirname,'..','My_Storybook.html'),'utf8');
for(const match of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)) new vm.Script(match[1]);
const ids = [...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
assert.equal(new Set(ids).size,ids.length,'duplicate DOM id');
assert(!html.includes('/* APP_'),'unresolved build placeholder');
assert(!/<(?:script|link)[^>]+(?:src|href)=["']https?:/i.test(html),'external runtime dependency');
console.log('PASS: portable media round-trip, previous takes, page identity, missing narration, invalid imports, Unicode TTS chunks, filenames, script syntax, DOM ids, self-contained build.');
